/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;

/**
 *
 * @author elmer
 */
public class ListModelView extends javax.swing.JFrame {

    /**
     * Creates new form ListModelView
     */
    public ListModelView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listColores = new javax.swing.JList<>();
        txtMensaje = new javax.swing.JLabel();
        bntColoresPrimarios = new javax.swing.JButton();
        btnColoresSecundarios = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listColoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listColores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 110));

        txtMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 370, 40));

        bntColoresPrimarios.setText("Colores Primarios");
        bntColoresPrimarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntColoresPrimariosActionPerformed(evt);
            }
        });
        jPanel1.add(bntColoresPrimarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 160, -1));

        btnColoresSecundarios.setText("Colores Secundarios");
        btnColoresSecundarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoresSecundariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnColoresSecundarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, -1));

        btnVaciar.setText("Vaciar");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntColoresPrimariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntColoresPrimariosActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = new DefaultListModel();
        modeloLista.addElement("Rojo");
        modeloLista.addElement("Amarillo");
        modeloLista.addElement("Azul");
        listColores.setModel(modeloLista);
    }//GEN-LAST:event_bntColoresPrimariosActionPerformed

    private void btnColoresSecundariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoresSecundariosActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = new DefaultListModel();
        modeloLista.addElement("Naranja");
        modeloLista.addElement("Verde");
        modeloLista.addElement("Morado");
        listColores.setModel(modeloLista);
    }//GEN-LAST:event_btnColoresSecundariosActionPerformed

    private void listColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listColoresMouseClicked
        // TODO add your handling code here:
        txtMensaje.setText("Elc color seleccionado es: " + listColores.getSelectedValue());
    }//GEN-LAST:event_listColoresMouseClicked

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modeloLista = new DefaultListModel();
        listColores.setModel(modeloLista);
    }//GEN-LAST:event_btnVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListModelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListModelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListModelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListModelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListModelView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntColoresPrimarios;
    private javax.swing.JButton btnColoresSecundarios;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listColores;
    private javax.swing.JLabel txtMensaje;
    // End of variables declaration//GEN-END:variables
}
