/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author elmer
 */
public class toggleButtonView extends javax.swing.JFrame {

    /**
     * Creates new form toggleButtonView
     */
    public toggleButtonView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        btnOffice.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnSistemaOperativo = new javax.swing.JToggleButton();
        btnOffice = new javax.swing.JToggleButton();
        btnAntivirus = new javax.swing.JToggleButton();
        lblSistemaOperativo = new javax.swing.JLabel();
        lblOffice = new javax.swing.JLabel();
        lblAntivirus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Precio Base");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, -1));

        lblTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 250, 30));

        btnSistemaOperativo.setText("Sistema Operativo");
        jPanel1.add(btnSistemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, -1));

        btnOffice.setText("Office");
        jPanel1.add(btnOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, -1));

        btnAntivirus.setText("Antivirus");
        jPanel1.add(btnAntivirus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        lblSistemaOperativo.setText("200");
        jPanel1.add(lblSistemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 69, 90, 30));

        lblOffice.setText("150");
        jPanel1.add(lblOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, 30));

        lblAntivirus.setText("100");
        jPanel1.add(lblAntivirus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double precioBase, precioSistemaOperativo, precioOffice, precioAntivirus, precioTotal;
        if (txtPrecioBase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa el precio base!");
        } else {
            precioBase = Double.parseDouble(txtPrecioBase.getText());
            precioSistemaOperativo = Double.parseDouble(lblSistemaOperativo.getText());
            precioOffice = Double.parseDouble(lblOffice.getText());
            precioAntivirus = Double.parseDouble(lblAntivirus.getText());
            precioTotal = precioBase;

            if (btnSistemaOperativo.isSelected()) {
                precioTotal += precioSistemaOperativo;
            }
            if (btnOffice.isSelected()) {
                precioTotal += precioOffice;
            }
            if (btnAntivirus.isSelected()) {
                precioTotal += precioAntivirus;
            }
            lblTotal.setText(String.valueOf(precioTotal));
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toggleButtonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toggleButtonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toggleButtonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toggleButtonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toggleButtonView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAntivirus;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JToggleButton btnOffice;
    private javax.swing.JToggleButton btnSistemaOperativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAntivirus;
    private javax.swing.JLabel lblOffice;
    private javax.swing.JLabel lblSistemaOperativo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
